name: Archive Artifact

on:
    push

jobs:
    archive_on:
        runs-on: ubuntu-latest
        steps:
            - name: Run ${{ github.run_id }}
              env:
                run_id: ${{ github.run_id }}
              run: |
                echo "hello" > $GITHUB_WORKSPACE/hello.txt
                echo ${run_id}
            
            - name: Archive
              uses: actions/upload-artifact@v7
              with:
                name: artifact.txt
                archive: false
                path: ${{ github.workspace }}/*.txt
              