on:
   pull_request:
     types: ["opened", "synchronize"]
jobs:
    test_pr:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout PR"
              uses: actions/checkout@v4
            
            - name: "Check files"
              run: |
                git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
            
              
