name: Workflow Outputs

on:
    workflow_dispatch:


jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup node
              uses: actions/setup-node@v3
            
            - name: Run script
              id: config_output
              run: |
                npm i .github/scripts/package.json
                node .github/scripts/index.js
            
            - name: See output
              run: | 
                 echo ${{ steps.outputs.config_output.MANIFEST_INFO }}
              
