name: Report PR Statistics

on:
    workflow_dispatch:
      inputs:
        PR_TYPES:
          options: ["READY_FOR_REVIEW", "DEPENDECY_UPDATES"]
          type: choice
          required: true

jobs:
    gather_prs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                repository: a9mansoo/GHA
                path: resources
            
            - name: Setup Node
              uses: actions/setup-node@v4
            
            - name: Install Dependencies
              run: |
                 npm i resources/.github/scripts/
            - name: Gather PRs based off of type ${{ github.inputs.PR_TYPES }}
              id: pr-info
              env:
                RUN_ID: ${{ github.run_id }}
                RULE_NAME: ${{ github.inputs.PR_TYPES }}
                CONFIG_FILE: ${{ github.workspace }}/resources/.github/pr-rules.json
                GH_TOKEN: ${{ secrets.GH_TOKEN }}
                REPOSITORY: ${{ github.inputs.REPOSITORY }}
              run: |
                npm run collect-prs
            
            - name: Archive PR Info
              uses: actions/upload-artifact@v7
              with:
                archive: false
                path: ${{ github.workspace }}/*.json
              