name: UT / Dev / Trigger


on:
    pull_request:
        types: [opened, synchronize]

jobs:
    call_reusable_workflow:
        uses: a9mansoo/Reusable-Workflows/.github/workflows/ut-dev-runner.yml@main
        with:
            REPOSITORY: ${{ github.repository }}
        secrets:
            token: ${{ github.GITHUB_TOKEN }}

