name: UT / Dev / Trigger


on:
    pull_request:
        types: [opened, synchronize, edited]

jobs:
    call_reusable_workflow:
        uses: a9mansoo/Reusbale-Workflows/.github/workflows/ut-dev-runner.yml@main
        with:
            REPOSITORY: ${{ github.repository }}
        secrets:
            token: ${{ secrets.REPO_TOKEN }}

